parameters :
    app_name : "EVFramework Skeleton Application"

    root_dir : /site/evframework-skeleton-application/web/
    secured_dir: /site/evframework-skeleton-application/web/tmp/secured
    production_mode: false

    root_url: http://skeleton.evaneos.com.dev

    cookie :
        domain : .evframework-skeleton-application.evaneos.com.dev

    default_locale:
        default: fr

    db :
        adapter : PDO_PGSQL
        params :
            host : 127.0.0.1
            port : 5432
            username : postgres
            password : postgres
            dbname : postgres

    memcached :
        host : 127.0.0.1
        port : 11211